<?php

namespace App\Enums;

/**
 * Lifecycle of a payroll run (ERD §A.5):
 * - draft    : generated by HR, not yet approved.
 * - approved : reviewed, ready to pay.
 * - paid     : disbursed — posts a cash-book expense and locks the period's
 *              attendance (Fase 6-2, ADR-0016).
 */
enum PayrollStatus: string
{
    case Draft = 'draft';
    case Approved = 'approved';
    case Paid = 'paid';

    public function label(): string
    {
        return match ($this) {
            self::Draft => 'Draft',
            self::Approved => 'Disetujui',
            self::Paid => 'Dibayar',
        };
    }
}
